apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: localsentinel
  name: localsentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
