apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: localsentinel-1
  name: localsentinel-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
