apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f dockerfileodilia.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: odilia-db-replication01
  name: odilia-db-replication01
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: odilia-db-replication01
