apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f dockerfileodilia.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: yelb-appserver
  name: yelb-appserver
spec:
  ports:
    - name: "4567"
      port: 4567
      targetPort: 4567
  selector:
    io.kompose.service: yelb-appserver
